[build]
  publish = "exampleSite/public"
  command = "hugo -s exampleSite --gc"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.87.0"

[context.production.environment]
  HUGO_BASEURL = "https://antora-default-ui-hugo-theme.netlify.app/"

[context.deploy-preview]
  command = "hugo -s exampleSite --gc --buildFuture -b $DEPLOY_PRIME_URL"
